#!/usr/bin/env python3
# Generated by Priority 1 Enhanced RAG Pipeline
# Test: add_enable_signal
# Description: Add an enable signal to control assignments in a Verilog module
# Complexity: medium
# Quality Score: 1.00
# Success: True
# Generated: 2025-07-19T22:11:07.228179
# Code Length: 2356 characters

# --- GENERATED CODE ---

#!/usr/bin/env python3
import sys
import os
import re
import argparse
from pyverilog.vparser.parser import parse
from pyverilog.vparser.ast import *

class TransformationVisitor:
    def __init__(self, enable_name=None):
        self.enable_name = enable_name
        self.changes_made = []
        self.found_modules = []

    def visit(self, node):
        if isinstance(node, ModuleDef):
            module_name = str(node.name)
            self.found_modules.append(module_name)
            if self.enable_name and module_name == self.enable_name:
                self.changes_made.append(f"Found module '{module_name}' to add enable signal")
        
        if isinstance(node, Node):
            for child in node.children():
                self.visit(child)

def transform_operation(input_file, output_file, enable_name=None):
    try:
        with open(input_file, "r") as f:
            content = f.read()
        
        ast, directives = parse([input_file])
        visitor = TransformationVisitor(enable_name)
        visitor.visit(ast)
        
        if enable_name:
            pattern = r'\bassign\s+(\w+)\s*=\s*(\w+);'
            replacement = f'if ({enable_name}) begin assign $1 = $2; end else begin assign $1 = 0; end'
            modified_content = re.sub(pattern, replacement, content)
            print(f"Added enable signal '{enable_name}' to module")
        else:
            modified_content = content
            print("No enable signal parameters provided")
        
        with open(output_file, "w") as f:
            f.write(modified_content)
        return True
        
    except Exception as e:
        print(f"Error: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="Add enable signal to control assignments in a Verilog module")
    parser.add_argument("input_file", help="Input Verilog file")
    parser.add_argument("output_file", help="Output Verilog file")
    parser.add_argument("--enable-name", help="Name of enable signal to add")
    
    args = parser.parse_args()
    if not os.path.exists(args.input_file):
        print(f"Error: Input file not found: {args.input_file}")
        return 1
    
    success = transform_operation(args.input_file, args.output_file, args.enable_name)
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())